FROM node:14-alpine as build

WORKDIR /app    

ARG BACKEND_HOST
ENV BACKEND_HOST=$BACKEND_HOST

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install

COPY . ./

RUN yarn build


FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]