version: "3.8"
services:
  postgres:
    volumes:
      - "${PWD}/db/volume:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  pgadmin:
    volumes:
      - ${PWD}/pgadmin/pgadmin_servers:/pgadmin4/pgadmin_servers
    ports:
      - 8080:8080

  redis:
    volumes:
      - ${PWD}/redis/redis.conf:/redis.conf
    ports: 
      - 6379:6379
          
  backend:
    volumes: 
      - "${PWD}/backend:/app"
    ports: 
      - 8001:80

  frontend:
    volumes:
      - "${PWD}/frontend:/app"
    ports: 
      - 4000:80
