version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: airbnb-clone-server-db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    container_name: airbnb-clone-server-db-admin
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

  redis:
    build: ./backend/db/redis
    container_name: airbnb-clone-server-redis
          
  backend:
    build: ./backend
    container_name: airbnb-clone-server-backend
    depends_on: 
      - postgres
      - redis
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_TIMEZONE=${DB_TIMEZONE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  frontend:
    build: ./frontend
    container_name: airbnb-clone-server-frontend
    depends_on:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3