root = "." 
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/app/engine cmd/server/main.go"

bin = "tmp/app"
full_bin = "./tmp/app/engine"

include_ext = ["go", "yaml", "graphqls"]
exclude_dir = ["tmp", "db"]
delay = 1000 # ms

[log]
# Show log time
time = true

[misc]
# Delete tmp directory on exit
clean_on_exit = true