version: "3.8"
# https://betterprogramming.pub/create-a-private-postgresql-database-for-your-development-environment-in-seconds-b781640ed01b
services:
  postgres:
    image: postgres:latest
    container_name: airbnb-clone-server-db
    volumes:
      - "${PWD}/db/volume:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  pgadmin:
    image: dpage/pgadmin4
    container_name: airbnb-clone-server-db-admin
    volumes:
      - ${PWD}/db/pgadmin_servers:/pgadmin4/pgadmin_servers
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  redis:
    image: redis:alpine
    container_name: airbnb-clone-server-redis
    ports: 
        - 6379:6379
    volumes:
      - ./db/redis/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
          
  server:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: airbnb-clone-server
    ports: 
      - 8001:8001
    depends_on: 
      - postgres
      - redis
    volumes: 
      - "${PWD}:/app"
